from app.services.ai_service import AIService
from app.services.parser_service import NaturalLanguageParserService
from app.services.irregular_income import IrregularIncomeEngine
from app.services.budget_service import BudgetService
from app.services.goal_service import GoalService
from app.services.voice_service import VoiceService
from app.services.scam_service import ScamService
from app.services.game_service import GameService
from app.services.simulator_service import SimulatorService
